import { contextBridge, ipcRenderer, webUtils } from 'electron'
import type { DesktopAPI } from '../shared/api'
const api:DesktopAPI={
 platform:process.platform,
 onMenuCommand:callback=>{const listener=(_event:unknown,command:import('../shared/native-menu').MenuCommand)=>callback(command);ipcRenderer.on('menu:command',listener);return()=>ipcRenderer.removeListener('menu:command',listener)},
 syncMenu:state=>ipcRenderer.invoke('menu:state',state),
 onCloseRequest:callback=>{const listener=async(_event:unknown,token:string)=>{try{await callback();ipcRenderer.send('window:flushed',token)}catch(error){ipcRenderer.send('window:flushed',token,error instanceof Error?error.message:String(error))}};ipcRenderer.on('window:flush',listener);return()=>ipcRenderer.removeListener('window:flush',listener)},
 updateStatus:()=>ipcRenderer.invoke('updates:status'),
 checkForUpdates:()=>ipcRenderer.invoke('updates:check'),
 downloadUpdate:()=>ipcRenderer.invoke('updates:download'),
 installUpdate:()=>ipcRenderer.invoke('updates:install'),
 onUpdate:callback=>{const listener=(_event:unknown,data:Parameters<typeof callback>[0])=>callback(data);ipcRenderer.on('updates:progress',listener);return()=>ipcRenderer.removeListener('updates:progress',listener)},
 startAnalysis:projectId=>ipcRenderer.invoke('analysis:start',projectId),
 analysisStatus:()=>ipcRenderer.invoke('analysis:status'),
 cancelAnalysis:id=>ipcRenderer.invoke('analysis:cancel',id),
 onAnalysis:callback=>{const listener=(_event:unknown,data:Parameters<typeof callback>[0])=>callback(data);ipcRenderer.on('analysis:progress',listener);return()=>ipcRenderer.removeListener('analysis:progress',listener)},
 startSeparation:(projectId,sourceId,targets,clipId)=>ipcRenderer.invoke('separation:start',projectId,sourceId,targets,clipId),
 separationStatus:()=>ipcRenderer.invoke('separation:status'),
 cancelSeparation:id=>ipcRenderer.invoke('separation:cancel',id),
 onSeparation:callback=>{const listener=(_event:unknown,data:Parameters<typeof callback>[0])=>callback(data);ipcRenderer.on('separation:progress',listener);return()=>ipcRenderer.removeListener('separation:progress',listener)},
 listArchivedProjects:()=>ipcRenderer.invoke('projects:archived'),
 restoreArchivedProject:id=>ipcRenderer.invoke('projects:restore',id),
 purgeArchivedProject:id=>ipcRenderer.invoke('projects:purge-archived',id),
 listProjects:()=>ipcRenderer.invoke('projects:list'),
 openProject:(id)=>ipcRenderer.invoke('projects:open',id),
 importDroppedAudio:file=>{const source=webUtils.getPathForFile(file);if(!source)return Promise.reject(new Error('Choose a local audio file'));return ipcRenderer.invoke('projects:import-dropped',source)},
 importAudio:()=>ipcRenderer.invoke('projects:import'),
 saveProject:(id,edits)=>ipcRenderer.invoke('projects:save',id,edits),
 editClip:(id,action)=>ipcRenderer.invoke('clips:edit',id,action),
 editTrack:(id,action)=>ipcRenderer.invoke('tracks:edit',id,action),
 deleteProject:(id,purge)=>ipcRenderer.invoke('projects:delete',id,purge),
 exportTracks:(id,tracks,format,clipIds,options)=>ipcRenderer.invoke('tracks:export',id,tracks,format,clipIds,options),
 openExportDirectory:directory=>ipcRenderer.invoke('exports:open-directory',directory),
 listModels:()=>ipcRenderer.invoke('models:list'),
 downloadModel:(id)=>ipcRenderer.invoke('models:download',id),
 cancelModelDownload:()=>ipcRenderer.invoke('models:cancel'),
 deleteModel:(id)=>ipcRenderer.invoke('models:delete',id),
 onModelProgress:(callback)=>{const listener=(_event:unknown,data:Parameters<typeof callback>[0])=>callback(data);ipcRenderer.on('models:progress',listener);return()=>ipcRenderer.removeListener('models:progress',listener)},
 settingsDirectories:()=>ipcRenderer.invoke('settings:directories'),
 chooseSettingsDirectory:kind=>ipcRenderer.invoke('settings:choose-directory',kind),
 resetSettingsDirectory:kind=>ipcRenderer.invoke('settings:reset-directory',kind),
 openDocumentation:topic=>ipcRenderer.invoke('docs:open',topic),
 choosePythonInterpreter:()=>ipcRenderer.invoke('settings:choose-python'),
 resetPythonInterpreter:()=>ipcRenderer.invoke('settings:reset-python'),
 getSettings:()=>ipcRenderer.invoke('settings:get'),
 probeDevice:()=>ipcRenderer.invoke('device:probe'),
 saveSettings:(settings)=>ipcRenderer.invoke('settings:save',settings)
}
contextBridge.exposeInMainWorld('printemps',api)
