import {preserveCompositionEscape} from './keyboard'
import {ErrorNotice} from './error-notice'
import {useMenuCommand} from './native-menu'
import {useId,useState} from 'react'
import {formatTimecode} from '../shared/timecode'
import * as Dialog from '@radix-ui/react-dialog'
import type {Project} from '../shared/domain'
import {trackClips,clipDuration} from '../shared/clips'
type Alignment='clip'|'timeline'
function AlignmentRow({en,value,onChange,disabled,id}:{en:boolean;value:Alignment;onChange:(value:Alignment)=>void;disabled:boolean;id:string}){
 const t=(a:string,b:string)=>en?b:a
 return <div className="export-format-row"><span id={id}>{t('对齐','Alignment')}</span><div className="export-format-options" role="radiogroup" aria-labelledby={id} data-value={value}>{(['clip','timeline'] as const).map(option=><label key={option}><input type="radio" name={id} value={option} checked={value===option} disabled={disabled} onChange={()=>onChange(option)}/><span>{option==='clip'?t('剪辑范围','Clip range'):t('项目时间轴','Project timeline')}</span></label>)}</div></div>
}
export function ExportDialog({project,en,trackId,clipId,menuOwner=false,beforeExport,disabled=false}:{project:Project;en:boolean;trackId?:string;clipId?:string;menuOwner?:boolean;disabled?:boolean;beforeExport:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[format,setFormat]=useState<'wav'|'flac'>('wav'),[alignment,setAlignment]=useState<Alignment>('clip'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[directory,setDirectory]=useState(''),[error,setError]=useState('')
 const formatId=useId(),alignmentId=useId()
 const t=(a:string,b:string)=>en?b:a,track=project.tracks.find(t=>t.id===trackId),clip=track&&trackClips(track).find(c=>c.id===clipId&&!c.hidden)
 function show(){if(disabled||!clip)return;setMessage('');setError('');setDirectory('');setOpen(true)}
 useMenuCommand('export',()=>{if(menuOwner)show()})
 async function run(){if(!track||!clip)return;setBusy(true);setMessage('');setError('');setDirectory('');try{await beforeExport();const result=await window.printemps.exportTracks(project.id,[track.id],format,[clip.id],{alignment});if(result){setDirectory(result.count>0?result.directory:'');if(result.failure)setError(result.failure.message);else setMessage(t('导出完成','Export complete'))}}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <Dialog.Root open={open} onOpenChange={v=>{if(busy)return;if(v)show();else setOpen(false)}}><Dialog.Trigger disabled={disabled||!clip} className="secondary">{menuOwner?t('导出','Export'):t('导出剪辑','Export clip')}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content onEscapeKeyDown={preserveCompositionEscape} className="dialog clip-export-dialog"><Dialog.Title>{t('导出剪辑','Export clip')}</Dialog.Title><Dialog.Description asChild><div className="export-clip-summary"><strong style={{color:track?.color}}>{clip?.name}</strong><span>{t('时长','Duration')} {clip?formatTimecode(clipDuration(clip)):'—'}</span></div></Dialog.Description><div className="export-format-row"><span id={formatId}>{t('格式','Format')}</span><div className="export-format-options" role="radiogroup" aria-labelledby={formatId} data-value={format}>{(['wav','flac'] as const).map(value=><label key={value}><input type="radio" name={formatId} value={value} checked={format===value} disabled={busy} onChange={()=>setFormat(value)}/><span>{value.toUpperCase()}</span></label>)}</div></div><AlignmentRow en={en} value={alignment} onChange={setAlignment} disabled={busy} id={alignmentId}/><p className="export-specification">{format==='wav'?'24-bit PCM':'24-bit FLAC'} · {track?`${track.sampleRate/1000} kHz`:''} · {track?.channels===1?'Mono':track?.channels===2?'Stereo':`${track?.channels??0} ${t('声道','channels')}`}{alignment==='timeline'&&clip&&clip.offset>0&&<> · {t(`项目时间轴导出会在开头补 ${formatTimecode(clip.offset)} 空白`,`Timeline export prepends ${formatTimecode(clip.offset)} of silence`)}</>}</p>{message&&<p role="status" className="export-success">{message}</p>}{error&&<ErrorNotice kind="export" message={error} en={en}/>}<div className="dialog-actions">{directory&&<button disabled={busy} onClick={()=>void window.printemps.openExportDirectory(directory).catch(e=>setError(String(e)))}>{t('打开文件夹','Open folder')}</button>}<Dialog.Close disabled={busy}>{t('关闭','Close')}</Dialog.Close><button className="primary" disabled={busy||!clip} onClick={run}>{busy?t('正在导出…','Exporting…'):t('导出','Export')}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}

/** Header export: every visible track's clips as independent files, with the same format and alignment choices. */
export function TracksExportDialog({project,en,beforeExport,disabled=false}:{project:Project;en:boolean;beforeExport:()=>Promise<void>;disabled?:boolean}){
 const [open,setOpen]=useState(false),[format,setFormat]=useState<'wav'|'flac'>('wav'),[alignment,setAlignment]=useState<Alignment>('timeline'),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[directory,setDirectory]=useState(''),[error,setError]=useState('')
 const formatId=useId(),alignmentId=useId()
 const t=(a:string,b:string)=>en?b:a
 const tracks=project.tracks.filter(track=>!track.hidden&&track.role!=='original'&&trackClips(track).some(clip=>!clip.hidden))
 function show(){if(disabled||!tracks.length)return;setMessage('');setError('');setDirectory('');setSelected(tracks.map(track=>track.id));setOpen(true)}
 useMenuCommand('export',show)
 async function run(){if(!selected.length)return;setBusy(true);setMessage('');setError('');setDirectory('');try{await beforeExport();const result=await window.printemps.exportTracks(project.id,selected,format,undefined,{alignment});if(result){setDirectory(result.count>0?result.directory:'');if(result.failure)setError(result.failure.message);else setMessage(t(`已导出 ${result.count} 个文件`,`Exported ${result.count} ${result.count===1?'file':'files'}`))}}catch(e){setError(String(e))}finally{setBusy(false)}}
 const sample=tracks[0]
 return <Dialog.Root open={open} onOpenChange={v=>{if(busy)return;if(v)show();else setOpen(false)}}><Dialog.Trigger disabled={disabled||!tracks.length} className="secondary">{t('导出','Export')}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content onEscapeKeyDown={preserveCompositionEscape} className="dialog clip-export-dialog tracks-export-dialog"><Dialog.Title>{t('导出音轨','Export tracks')}</Dialog.Title><Dialog.Description className="dialog-lead">{t('分离结果的可见剪辑各导出为独立文件；原始音频不在此列。','Each visible clip of the chosen result tracks becomes its own file; the original audio is not included.')}</Dialog.Description>
  <ul className="export-track-list">{tracks.map(track=>{const clips=trackClips(track).filter(clip=>!clip.hidden),duration=clips.reduce((sum,clip)=>sum+clipDuration(clip),0);return <li key={track.id}><label><input type="checkbox" checked={selected.includes(track.id)} disabled={busy} onChange={e=>setSelected(current=>e.target.checked?[...current,track.id]:current.filter(id=>id!==track.id))}/><span className="export-track-name" style={{color:track.color}}>{track.name}</span><small>{clips.length>1?t(`${clips.length} 个剪辑`,`${clips.length} clips`)+' · ':''}{formatTimecode(duration)}</small></label></li>})}</ul>
  <div className="export-format-row"><span id={formatId}>{t('格式','Format')}</span><div className="export-format-options" role="radiogroup" aria-labelledby={formatId} data-value={format}>{(['wav','flac'] as const).map(value=><label key={value}><input type="radio" name={formatId} value={value} checked={format===value} disabled={busy} onChange={()=>setFormat(value)}/><span>{value.toUpperCase()}</span></label>)}</div></div>
  <AlignmentRow en={en} value={alignment} onChange={setAlignment} disabled={busy} id={alignmentId}/>
  <p className="export-specification">{format==='wav'?'24-bit PCM':'24-bit FLAC'} · {sample?`${sample.sampleRate/1000} kHz`:''} · {sample?.channels===1?'Mono':'Stereo'} · {alignment==='timeline'?t('按项目时间轴对齐，开头补空白','Aligned to the project timeline with leading silence'):t('仅导出剪辑本身的范围','Clip ranges only')}</p>
  {message&&<p role="status" className="export-success">{message}</p>}{error&&<ErrorNotice kind="export" message={error} en={en}/>}
  <div className="dialog-actions">{directory&&<button disabled={busy} onClick={()=>void window.printemps.openExportDirectory(directory)}>{t('打开文件夹','Open folder')}</button>}<Dialog.Close disabled={busy}>{t('关闭','Close')}</Dialog.Close><button className="primary" disabled={busy||!selected.length} onClick={run}>{busy?t('正在导出…','Exporting…'):t(`导出 ${selected.length} 条音轨`,`Export ${selected.length} ${selected.length===1?'track':'tracks'}`)}</button></div>
 </Dialog.Content></Dialog.Portal></Dialog.Root>
}
