import {preserveCompositionEscape} from './keyboard'
import {ErrorNotice} from './error-notice'
import {useMenuCommand} from './native-menu'
import {useId,useState} from 'react'
import {formatTimecode} from '../shared/timecode'
import * as Dialog from '@radix-ui/react-dialog'
import type {Project} from '../shared/domain'
import {trackClips,clipDuration} from '../shared/clips'
export function ExportDialog({project,en,trackId,clipId,menuOwner=false,beforeExport,disabled=false}:{project:Project;en:boolean;trackId?:string;clipId?:string;menuOwner?:boolean;disabled?:boolean;beforeExport:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[format,setFormat]=useState<'wav'|'flac'>('wav'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[directory,setDirectory]=useState(''),[error,setError]=useState('')
 const formatId=useId()
 const t=(a:string,b:string)=>en?b:a,track=project.tracks.find(t=>t.id===trackId),clip=track&&trackClips(track).find(c=>c.id===clipId&&!c.hidden)
 function show(){if(disabled||!clip)return;setMessage('');setError('');setDirectory('');setOpen(true)}
 useMenuCommand('export',()=>{if(menuOwner)show()})
 async function run(){if(!track||!clip)return;setBusy(true);setMessage('');setError('');setDirectory('');try{await beforeExport();const result=await window.printemps.exportTracks(project.id,[track.id],format,[clip.id]);if(result){setDirectory(result.count>0?result.directory:'');if(result.failure)setError(result.failure.message);else setMessage(t('导出完成','Export complete'))}}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <Dialog.Root open={open} onOpenChange={v=>{if(busy)return;if(v)show();else setOpen(false)}}><Dialog.Trigger disabled={disabled||!clip} className="secondary">{menuOwner?t('导出','Export'):t('导出剪辑','Export clip')}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content onEscapeKeyDown={preserveCompositionEscape} className="dialog clip-export-dialog"><Dialog.Title>{t('导出剪辑','Export clip')}</Dialog.Title><Dialog.Description asChild><div className="export-clip-summary"><strong style={{color:track?.color}}>{clip?.name}</strong><span>{t('时长','Duration')} {clip?formatTimecode(clipDuration(clip)):'—'}</span></div></Dialog.Description><div className="export-format-row"><span id={formatId}>{t('格式','Format')}</span><div className="export-format-options" role="radiogroup" aria-labelledby={formatId} data-value={format}>{(['wav','flac'] as const).map(value=><label key={value}><input type="radio" name={formatId} value={value} checked={format===value} disabled={busy} onChange={()=>setFormat(value)}/><span>{value.toUpperCase()}</span></label>)}</div></div><p className="export-specification">{format==='wav'?'24-bit PCM':'24-bit FLAC'} · {track?`${track.sampleRate/1000} kHz`:''} · {track?.channels===1?'Mono':track?.channels===2?'Stereo':`${track?.channels??0} ${t('声道','channels')}`}</p>{message&&<p role="status" className="export-success">{message}</p>}{error&&<ErrorNotice kind="export" message={error} en={en}/>}<div className="dialog-actions">{directory&&<button disabled={busy} onClick={()=>void window.printemps.openExportDirectory(directory).catch(e=>setError(String(e)))}>{t('打开文件夹','Open folder')}</button>}<Dialog.Close disabled={busy}>{t('关闭','Close')}</Dialog.Close><button className="primary" disabled={busy||!clip} onClick={run}>{busy?t('正在导出…','Exporting…'):t('导出','Export')}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
