import {ErrorNotice} from './error-notice'
import {useEffect,useState} from 'react'
import {stemLabel,matchesStem,formatModelBytes} from '../shared/stems'
import * as Dialog from '@radix-ui/react-dialog'
export function ModelLibrary({en}:{en:boolean}){
 const [open,setOpen]=useState(false),[models,setModels]=useState<{id:string;bytes:number;cached:boolean}[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[progress,setProgress]=useState(0)
 const [loading,setLoading]=useState(false),[directory,setDirectory]=useState(''),[removing,setRemoving]=useState(false)
 const t=(a:string,b:string)=>en?b:a
 async function refresh(){setLoading(true);setError('');try{const [items,folders]=await Promise.all([window.printemps.listModels(),window.printemps.settingsDirectories()]);setModels(items);setDirectory(folders.modelDirectory)}catch(e){setError(String(e))}finally{setLoading(false)}}
 useEffect(()=>window.printemps?.onModelProgress(p=>{if(p.modelId===busy)setProgress(p.total>0?p.received/p.total:0)}),[busy])
 async function action(id:string,remove:boolean){setBusy(id);setRemoving(remove);setError('');setProgress(0);try{if(remove)await window.printemps.deleteModel(id);else await window.printemps.downloadModel(id);await refresh()}catch(e){setError(String(e))}finally{setBusy('')}}
 return <Dialog.Root open={open} onOpenChange={v=>{setOpen(v);if(v)void refresh()}}><Dialog.Trigger>{t('模型管理','Models')}{busy&&!removing&&<span aria-label={t('下载中','Downloading')}> · {Math.round(progress*100)}%</span>}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog history-dialog"><Dialog.Title>{t('模型管理','Model library')}</Dialog.Title><Dialog.Description>{t('按需下载声部模型；删除缓存不会删除项目结果。','Download models as needed. Removing a model preserves project results.')}</Dialog.Description><p className="model-cache-location" title={directory}>{t('缓存位置：','Cache folder: ')}{directory||t('读取中…','Loading…')}</p><input aria-label={t('搜索模型','Search models')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('搜索模型名称','Search model name')}/><ErrorNotice message={error} en={en} kind="download"/><div className="model-library-status">{busy&&<div className="model-active-task"><span role="status">{removing?t('正在删除：','Removing: '):t('正在下载：','Downloading: ')}{stemLabel(busy,en)}</span>{!removing&&<><progress aria-label={t('模型下载进度','Model download progress')} value={progress} max={1}/><span>{Math.round(progress*100)}%</span><button onClick={()=>void window.printemps.cancelModelDownload().catch(e=>setError(String(e)))}>{t('取消','Cancel')}</button></>}</div>}{loading&&<p role="status">{t('正在校验本地模型…','Verifying cached models…')}</p>}{error&&<button disabled={loading||!!busy} onClick={()=>void refresh()}>{t('重新读取','Reload models')}</button>}</div><div className="history-list">{!loading&&!error&&!models.some(m=>matchesStem(m.id,query))&&<p>{t('没有匹配模型，请尝试其它关键词。','No matching models. Try another search.')}</p>}{models.filter(m=>matchesStem(m.id,query)).map(m=><div className="history-row" key={m.id}><div style={{flex:1}}><strong>{stemLabel(m.id,en)}</strong><small>{m.id}</small><small>{formatModelBytes(m.bytes)} · {m.cached?t('已缓存','Cached'):t('未下载','Not downloaded')}</small></div><button disabled={!!busy||loading} onClick={()=>action(m.id,m.cached)}>{busy===m.id?t('处理中…','Working…'):m.cached?t('删除','Remove'):t('下载','Download')}</button></div>)}</div><Dialog.Close>{t('关闭','Close')}</Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
}
