import {preserveCompositionEscape} from './keyboard'
import type {Settings} from '../shared/domain'
import {useMenuCommand} from './native-menu'
import {ArchiveIcon,MagnifyingGlassIcon,ArrowLeftIcon} from '@radix-ui/react-icons'
import {ErrorNotice} from './error-notice'
import {useEffect,useState} from 'react'
import {stemLabel,matchesStem,formatModelBytes} from '../shared/stems'
import manifest from '../shared/model-manifest.json'
import * as Dialog from '@radix-ui/react-dialog'
export function ModelLibrary({en,onOpenChange,onSettingsChange}:{en:boolean;onOpenChange:(open:boolean)=>void;onSettingsChange:(settings:Settings)=>void}){
 const [open,setOpen]=useState(false),[models,setModels]=useState<{id:string;bytes:number;cached:boolean}[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[progress,setProgress]=useState(0)
 const [loading,setLoading]=useState(false),[directory,setDirectory]=useState(''),[removing,setRemoving]=useState(false)
 const [filter,setFilter]=useState<'all'|'cached'|'missing'>('all'),[page,setPage]=useState(0)
 const [changingDirectory,setChangingDirectory]=useState(false)
 useEffect(()=>{onOpenChange(open);return()=>onOpenChange(false)},[open,onOpenChange])
 async function changeDirectory(){setChangingDirectory(true);setError('');try{const settings=await window.printemps.chooseSettingsDirectory('modelDirectory');if(settings){onSettingsChange(settings);await refresh()}}catch(e){setError(String(e))}finally{setChangingDirectory(false)}}
 const t=(a:string,b:string)=>en?b:a
 const filtered=models.filter(m=>matchesStem(m.id,query)&&(filter==='all'||m.cached===(filter==='cached'))).sort((a,b)=>Number(b.cached)-Number(a.cached))
 const pages=Math.max(1,Math.ceil(filtered.length/5)),currentPage=Math.min(page,pages-1)
 const cached=models.filter(m=>m.cached)
 useEffect(()=>setPage(0),[query,filter])
 async function refresh(){setLoading(true);setError('');try{const [items,folders]=await Promise.all([window.printemps.listModels(),window.printemps.settingsDirectories()]);setModels(items);setDirectory(folders.modelDirectory)}catch(e){setError(String(e))}finally{setLoading(false)}}
 useEffect(()=>window.printemps?.onModelProgress(p=>{if(p.modelId===busy)setProgress(p.total>0?p.received/p.total:0)}),[busy])
 async function action(id:string,remove:boolean){setBusy(id);setRemoving(remove);setError('');setProgress(0);try{if(remove)await window.printemps.deleteModel(id);else await window.printemps.downloadModel(id);await refresh()}catch(e){setError(String(e))}finally{setBusy('')}}
 useMenuCommand('models',()=>{setOpen(true);void refresh()})
 return <Dialog.Root open={open} onOpenChange={v=>{setOpen(v);if(v)void refresh()}}><Dialog.Trigger className="icon model-library-trigger" aria-label={t('模型管理','Models')} title={t('模型管理','Models')}><ArchiveIcon/>{busy&&!removing&&<span aria-label={t('下载中','Downloading')}> · {Math.round(progress*100)}%</span>}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay model-library-overlay"/><Dialog.Content onEscapeKeyDown={preserveCompositionEscape} onOpenAutoFocus={e=>e.preventDefault()} className="model-library-page">
 <div className="model-library-intro"><Dialog.Close className="icon back-button model-library-back" aria-label={t('返回','Back')} title={t('返回','Back')}><ArrowLeftIcon/></Dialog.Close><div><small className="eyebrow">MODEL LIBRARY</small><Dialog.Title>{t('你的声部工具箱','Your stem toolbox')}</Dialog.Title><Dialog.Description>{t('53 种目标声部。用到哪个，下载哪个。','53 target stems. Download the ones you need.')}</Dialog.Description></div></div>
 <div className="model-cache-summary"><div><strong>{t('已缓存','Cached')} {cached.length} / {models.length||53}</strong><small>{formatModelBytes(cached.reduce((sum,m)=>sum+m.bytes,0))}</small></div><div><small>{t('模型存储位置','Model cache folder')}</small><p title={directory}>{directory||t('读取中…','Loading…')}</p></div><button disabled={!!busy||loading||changingDirectory} onClick={()=>void changeDirectory()}>{t('更改位置','Change location')}</button></div>
 <div className="model-library-search"><label><MagnifyingGlassIcon/><input aria-label={t('搜索模型','Search models')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('搜索模型名称或乐器','Search model name or instrument')}/></label><div className="model-library-filters" role="group" aria-label={t('模型状态','Model status')} data-value={filter}><span aria-hidden="true"/>{(['all','cached','missing'] as const).map((value,index)=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{[t('全部','All'),t('已缓存','Cached'),t('未下载','Not downloaded')][index]}</button>)}</div></div>
 <ErrorNotice message={error} en={en} kind="download"/><div className="model-library-status">{busy&&<div className="model-active-task"><span role="status">{removing?t('正在删除：','Removing: '):t('正在下载：','Downloading: ')}{stemLabel(busy,en)}</span>{!removing&&<><div className="task-progress" role="progressbar" aria-label={t('模型下载进度','Model download progress')} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress*100)}><div style={{width:`${Math.max(0,Math.min(1,progress))*100}%`}}/></div><span>{Math.round(progress*100)}%</span><button onClick={()=>void window.printemps.cancelModelDownload().catch(e=>setError(String(e)))}>{t('取消','Cancel')}</button></>}</div>}{loading&&<p role="status">{t('正在校验本地模型…','Verifying cached models…')}</p>}{error&&<button disabled={loading||!!busy} onClick={()=>void refresh()}>{t('重新读取','Reload models')}</button>}</div>
 <div className="model-table-wrap"><table className="model-table"><thead><tr><th>{t('声部 / 模型文件','Stem / model file')}</th><th>{t('权重大小','Weights')}</th><th>{t('状态','Status')}</th><th>{t('操作','Action')}</th></tr></thead><tbody>{filtered.slice(currentPage*5,currentPage*5+5).map(m=><tr key={m.id}><td><strong>{stemLabel(m.id,en)}</strong><small>{manifest.models.find(model=>model.id===m.id)?.weight.path.split('/').at(-1)||m.id}</small></td><td>{formatModelBytes(m.bytes)}</td><td><span className={m.cached?'model-cached':''}>{m.cached?'● ':''}{m.cached?t('已缓存','Cached'):t('未下载','Not downloaded')}</span></td><td><button className={m.cached?'':'primary'} disabled={!!busy||loading||changingDirectory} onClick={()=>action(m.id,m.cached)}>{busy===m.id?t('处理中…','Working…'):m.cached?t('删除缓存','Remove cache'):t('下载','Download')}</button></td></tr>)}</tbody></table>{!loading&&!error&&!filtered.length&&<p>{t('没有匹配模型，请尝试其它关键词。','No matching models. Try another search.')}</p>}</div>
 <div className="model-library-footer"><small className="model-library-note">{t('每个模型附带约 1.6 kB 配置文件。删除缓存不会删除音频或分离结果。','Each model ships with a ~1.6 kB config file. Removing a cache never deletes audio or separation results.')}</small><span>{filtered.length?currentPage*5+1:0}–{Math.min((currentPage+1)*5,filtered.length)} / {filtered.length}</span><button aria-label={t('上一页','Previous page')} disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>‹</button><button aria-label={t('下一页','Next page')} disabled={currentPage>=pages-1} onClick={()=>setPage(currentPage+1)}>›</button></div>
 </Dialog.Content></Dialog.Portal></Dialog.Root>
}
