import {useState} from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import * as Switch from '@radix-ui/react-switch'
import {validateLoop,type LoopRange} from '../shared/playback'
export function TimelineControls({en,zoom,setZoom,loop,setLoop,duration,time}:{en:boolean;zoom:number;setZoom:(zoom:number)=>void;loop:LoopRange|null;setLoop:(range:LoopRange|null)=>void;duration:number;time:number}){
 const [open,setOpen]=useState(false),[start,setStart]=useState('0'),[end,setEnd]=useState('0'),[enabled,setEnabled]=useState(false),[error,setError]=useState('')
 const t=(zh:string,english:string)=>en?english:zh
 function apply(){try{const range=enabled?{start:Number(start),end:Number(end)}:null;validateLoop(range,duration);setLoop(range);setOpen(false)}catch{setError(t('循环范围需位于音频内，结束位置至少比起点晚 0.01 秒。','Choose a range within the audio, at least 0.01 seconds long.'))}}
 return <div className="timeline-navigation"><button aria-label={t('缩小时间轴','Zoom out')} disabled={zoom<=1} onClick={()=>setZoom(Math.max(1,zoom/2))}>−</button><button title={t('显示完整音频','Fit entire audio')} onClick={()=>setZoom(1)}>{zoom}×</button><button aria-label={t('放大时间轴','Zoom in')} disabled={zoom>=16} onClick={()=>setZoom(Math.min(16,zoom*2))}>＋</button><Dialog.Root open={open} onOpenChange={value=>{setOpen(value);if(value){setStart(String(loop?.start??0));setEnd(String(loop?.end??duration));setEnabled(!!loop);setError('')}}}><Dialog.Trigger aria-pressed={!!loop} className={loop?'selected':''}>{t('循环','Loop')}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog"><Dialog.Title>{t('循环试听','Loop playback')}</Dialog.Title><Dialog.Description>{t('循环范围使用秒为单位。','Loop positions are in seconds.')}</Dialog.Description><label>{t('开启循环','Enable loop')}<Switch.Root className="switch" checked={enabled} onCheckedChange={setEnabled}><Switch.Thumb className="switch-thumb"/></Switch.Root></label><label>{t('起点','Start')}<input aria-label={t('循环起点','Loop start')} type="number" min={0} max={duration} step={.01} value={start} onChange={e=>setStart(e.target.value)}/></label><button onClick={()=>setStart(time.toFixed(3))}>{t('游标设为起点','Set start to playhead')}</button><label>{t('终点','End')}<input aria-label={t('循环终点','Loop end')} type="number" min={0} max={duration} step={.01} value={end} onChange={e=>setEnd(e.target.value)}/></label><button onClick={()=>setEnd(time.toFixed(3))}>{t('游标设为终点','Set end to playhead')}</button>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><Dialog.Close>{t('取消','Cancel')}</Dialog.Close><button className="primary" onClick={apply}>{t('应用','Apply')}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root></div>
}
