import {useEffect,useState} from 'react'
import type {UpdateState} from '../shared/api'
export function UpdatePanel({en}:{en:boolean}){
 const [state,setState]=useState<UpdateState|null>(null),[error,setError]=useState('')
 const t=(zh:string,english:string)=>en?english:zh
 useEffect(()=>{let live=true;const receive=(next:UpdateState)=>{if(live)setState(next)};const off=window.printemps.onUpdate(receive);window.printemps.updateStatus().then(receive).catch(e=>setError(String(e)));return()=>{live=false;off()}},[])
 const labels:Record<UpdateState['phase'],string>={development:t('开发版本暂不检查更新','Updates are unavailable in development'),idle:t('检查新版本','Check for a new version'),checking:t('正在检查更新…','Checking for updates…'),available:t('有新版本可用','A new version is available'),current:t('已是最新版本','You are up to date'),downloading:t('正在下载更新…','Downloading update…'),ready:t('更新已就绪，重启后安装','Update ready; restart to install'),installing:t('正在重启…','Restarting…'),error:t('更新失败，请重试','Update failed. Please retry')}
 async function action(kind:'check'|'download'|'install'){setError('');try{if(kind==='check')setState(await window.printemps.checkForUpdates());else if(kind==='download')setState(await window.printemps.downloadUpdate());else await window.printemps.installUpdate()}catch(e){setError(String(e))}}
 return <section className="update-panel"><h3>{t('应用更新','Application updates')} {state&&<small>v{state.currentVersion}</small>}</h3><p role="status">{state?labels[state.phase]:t('正在读取版本…','Loading version…')}{state?.version&&` · v${state.version}`}</p>{state?.phase==='downloading'&&<><progress value={state.percent||0} max={100}/><small>{Math.round(state.percent||0)}%</small></>}{(error||state?.error)&&<p role="alert">{error||state?.error}</p>}<div className="dialog-actions">{state?.phase==='available'?<button onClick={()=>action('download')}>{t('下载更新','Download update')}</button>:state?.phase==='ready'?<button onClick={()=>action('install')}>{t('重启更新','Restart & update')}</button>:<button disabled={!state||['development','checking','downloading','installing'].includes(state.phase)} onClick={()=>action('check')}>{t('检查更新','Check for updates')}</button>}</div></section>
}
